name: 'Jira add comment'

on:
  workflow_call:
    inputs:
      jira_server:
        required: true
        type: string
      issue_id:
        required: true
        type: string
      comment:
        required: true
        type: string
      retry_count:
        default: 3
        required: false
        type: number
    secrets:
      username:
        required: true
      token:
        required: true

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: 'Add comment'
        run: |
          curl --request POST \
            --user "${{ secrets.username }}:${{ secrets.token }}" \
            --header 'Content-Type: application/json' \
            --retry "${{ inputs.retry_count }}" \
            --data "{ \"body\" : \"${{ inputs.comment }}\" }" \
            --url "${{ inputs.jira_server }}/rest/api/2/issue/${{ inputs.issue_id }}/comment"
